#include <config.hpp>

META(GLuint,    glCreateProgram)
META(void,      glDeleteProgram,            GLuint)
META(GLuint,    glCreateShader,             GLenum)
META(void,      glDeleteShader,             GLuint)
META(void,      glShaderSource,             GLuint, GLsizei, const GLchar *const *, const GLint *)
META(void,      glCompileShader,            GLuint)
META(void,      glGetShaderiv,              GLuint, GLenum, GLint *)
META(void,      glAttachShader,             GLuint, GLuint)
META(void,      glLinkProgram,              GLuint)
META(void,      glUseProgram,               GLuint)
META(void,      glGenBuffers,               GLsizei, GLuint *)
META(void,      glDeleteBuffers,            GLsizei, const GLuint *)
META(void,      glGenVertexArrays,          GLsizei, GLuint *)
META(void,      glDeleteVertexArrays,       GLsizei, const GLuint *)
META(void,      glBindVertexArray,          GLuint)
META(void,      glBindBuffer,               GLenum, GLuint)
META(void,      glBufferData,               GLenum, GLsizeiptr, const void *, GLenum)
META(void,      glVertexAttribPointer,      GLuint, GLint, GLenum, GLboolean, GLsizei, const void *)
META(void,      glVertexAttribIPointer,     GLuint, GLint, GLenum, GLsizei, const void *)
META(void,      glVertexAttribLPointer,     GLuint, GLint, GLenum, GLsizei, const void *)
META(void,      glEnableVertexAttribArray,  GLuint)
META(GLint,     glGetUniformLocation,       GLuint, const GLchar *)
META(void,      glUniform1i,                GLint, GLint)
META(void,      glUniformMatrix4fv,         GLint, GLsizei, GLboolean, const GLfloat *)
META(void *,    glMapBufferRange,           GLenum, GLintptr, GLsizeiptr, GLbitfield)
META(GLboolean, glUnmapBuffer,              GLenum)
META(void,      glActiveTexture,            GLenum)
META(void,      glBindAttribLocation,       GLuint, GLuint, const GLchar *)
META(void,      glGenFramebuffers,          GLsizei, GLuint *)
META(void,      glDeleteFramebuffers,       GLsizei, const GLuint *)
META(void,      glDeleteRenderbuffers,      GLsizei, const GLuint *)
META(void,      glBindFramebuffer,          GLenum, GLuint)
META(void,      glFramebufferTexture2D,     GLenum, GLenum, GLenum, GLuint, GLint)
META(GLenum,    glCheckFramebufferStatus,   GLenum)
META(void,      glBlitFramebuffer,          GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum )
META(GLuint,    glGetUniformBlockIndex,     GLuint, const GLchar *)
META(void,      glBindBufferBase,           GLenum, GLuint, GLuint)
META(void,      glUniformBlockBinding,      GLuint, GLuint, GLuint)
META(void,      glBufferSubData,            GLuint, GLintptr, GLsizeiptr, const void *)
META(void,      glDrawBuffers,              GLsizei, const GLenum *)
META(void,      glBlendFuncSeparate,        GLenum, GLenum, GLenum, GLenum )
META(void,      glBlendEquation,            GLenum)
META(void,      glBlendEquationSeparate,    GLenum, GLenum )

#if COMPILE_DEBUG
	META ( void, glGetShaderInfoLog, GLuint, GLsizei, GLsizei *, GLchar * )
#endif